# Generated by Django 4.2.10 on 2024-05-29 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_memo_post_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='memo',
        ),
    ]
